language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt --use-mirrors
  - pip install .
  - pip install coveralls --use-mirrors
script: nosetests --with-coverage --cover-package=datapusher
after_success:
  - coveralls